repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
-   repo: https://github.com/pre-commit/mirrors-eslint
    rev: 'v8.38.0'  # Use the sha / tag you want to point at
    hooks:
    -   id: eslint
        additional_dependencies:
        -   '@typescript-eslint/eslint-plugin@5.58.0'
        -   '@typescript-eslint/parser@5.58.0'
        -   eslint-plugin-vue@9.10.0
        types: [file]
        types_or: [javascript, jsx, ts, tsx, vue]
